CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "StoreProducts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "PointCost" integer NOT NULL,
    "Category" text NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StoreProducts" PRIMARY KEY ("Id")
);

CREATE TABLE "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "CognitoSub" text,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsSuspended" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LoyaltyPoints" integer NOT NULL,
    "Bio" text,
    "Website" text,
    "TwitterHandle" text,
    "InstagramHandle" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Events" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Location" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Capacity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "IsPublic" boolean NOT NULL,
    "Status" text NOT NULL,
    "IsSuspended" boolean NOT NULL,
    "PostponedDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ImageUrl" text,
    "InviteCode" text,
    "CreatedById" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Events_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "HostSubscriptions" (
    "SubscriberId" integer NOT NULL,
    "HostId" integer NOT NULL,
    "SubscribedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HostSubscriptions" PRIMARY KEY ("SubscriberId", "HostId"),
    CONSTRAINT "FK_HostSubscriptions_Users_HostId" FOREIGN KEY ("HostId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HostSubscriptions_Users_SubscriberId" FOREIGN KEY ("SubscriberId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PayoutRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizerId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "BankDetails" text NOT NULL,
    "Status" text NOT NULL,
    "AdminNotes" text,
    "RequestedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    CONSTRAINT "PK_PayoutRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayoutRequests_Users_OrganizerId" FOREIGN KEY ("OrganizerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserPurchases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchasedAt" timestamp with time zone NOT NULL,
    "PointsSpent" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    CONSTRAINT "PK_UserPurchases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPurchases_StoreProducts_ProductId" FOREIGN KEY ("ProductId") REFERENCES "StoreProducts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPurchases_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Announcements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_Announcements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Announcements_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Bookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookedAt" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "PointsEarned" integer NOT NULL,
    "ArePointsAwarded" boolean NOT NULL,
    "IsCheckedIn" boolean NOT NULL,
    "CheckedInAt" timestamp with time zone,
    "CheckInToken" text,
    "UserId" integer NOT NULL,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EventTags" (
    "EventId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_EventTags" PRIMARY KEY ("EventId", "TagId"),
    CONSTRAINT "FK_EventTags_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EventTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EventId" integer,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "IsPinned" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EventId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserFavorites" (
    "UserId" integer NOT NULL,
    "EventId" integer NOT NULL,
    "SavedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserFavorites" PRIMARY KEY ("UserId", "EventId"),
    CONSTRAINT "FK_UserFavorites_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WaitlistEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Position" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WaitlistEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WaitlistEntries_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WaitlistEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReviewReplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Comment" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_ReviewReplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReviewReplies_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReviewReplies_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReviewVotes" (
    "ReviewId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "IsLike" boolean NOT NULL,
    CONSTRAINT "PK_ReviewVotes" PRIMARY KEY ("ReviewId", "UserId"),
    CONSTRAINT "FK_ReviewVotes_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReviewVotes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Categories" ("Id", "Name")
VALUES (1, 'Conference');
INSERT INTO "Categories" ("Id", "Name")
VALUES (2, 'Workshop');
INSERT INTO "Categories" ("Id", "Name")
VALUES (3, 'Concert');
INSERT INTO "Categories" ("Id", "Name")
VALUES (4, 'Sports');
INSERT INTO "Categories" ("Id", "Name")
VALUES (5, 'Networking');
INSERT INTO "Categories" ("Id", "Name")
VALUES (6, 'Other');

INSERT INTO "Tags" ("Id", "Name")
VALUES (1, 'Music');
INSERT INTO "Tags" ("Id", "Name")
VALUES (2, 'Technology');
INSERT INTO "Tags" ("Id", "Name")
VALUES (3, 'Business');
INSERT INTO "Tags" ("Id", "Name")
VALUES (4, 'Arts');
INSERT INTO "Tags" ("Id", "Name")
VALUES (5, 'Food & Drink');
INSERT INTO "Tags" ("Id", "Name")
VALUES (6, 'Health & Wellness');
INSERT INTO "Tags" ("Id", "Name")
VALUES (7, 'Education');
INSERT INTO "Tags" ("Id", "Name")
VALUES (8, 'Entertainment');
INSERT INTO "Tags" ("Id", "Name")
VALUES (9, 'Gaming');
INSERT INTO "Tags" ("Id", "Name")
VALUES (10, 'Outdoor');
INSERT INTO "Tags" ("Id", "Name")
VALUES (11, 'Charity');
INSERT INTO "Tags" ("Id", "Name")
VALUES (12, 'Family');

CREATE INDEX "IX_Announcements_EventId" ON "Announcements" ("EventId");

CREATE UNIQUE INDEX "IX_Bookings_CheckInToken" ON "Bookings" ("CheckInToken");

CREATE INDEX "IX_Bookings_EventId" ON "Bookings" ("EventId");

CREATE UNIQUE INDEX "IX_Bookings_UserId_EventId" ON "Bookings" ("UserId", "EventId") WHERE "Status" = 'Confirmed';

CREATE INDEX "IX_Events_CategoryId" ON "Events" ("CategoryId");

CREATE INDEX "IX_Events_CreatedById" ON "Events" ("CreatedById");

CREATE INDEX "IX_EventTags_TagId" ON "EventTags" ("TagId");

CREATE INDEX "IX_HostSubscriptions_HostId" ON "HostSubscriptions" ("HostId");

CREATE INDEX "IX_Notifications_EventId" ON "Notifications" ("EventId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_PayoutRequests_OrganizerId" ON "PayoutRequests" ("OrganizerId");

CREATE INDEX "IX_ReviewReplies_ReviewId" ON "ReviewReplies" ("ReviewId");

CREATE INDEX "IX_ReviewReplies_UserId" ON "ReviewReplies" ("UserId");

CREATE UNIQUE INDEX "IX_Reviews_EventId_UserId" ON "Reviews" ("EventId", "UserId");

CREATE INDEX "IX_Reviews_UserId" ON "Reviews" ("UserId");

CREATE INDEX "IX_ReviewVotes_UserId" ON "ReviewVotes" ("UserId");

CREATE INDEX "IX_UserFavorites_EventId" ON "UserFavorites" ("EventId");

CREATE INDEX "IX_UserPurchases_ProductId" ON "UserPurchases" ("ProductId");

CREATE UNIQUE INDEX "IX_UserPurchases_UserId_ProductId" ON "UserPurchases" ("UserId", "ProductId");

CREATE UNIQUE INDEX "IX_Users_CognitoSub" ON "Users" ("CognitoSub") WHERE "CognitoSub" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_WaitlistEntries_EventId_UserId" ON "WaitlistEntries" ("EventId", "UserId");

CREATE INDEX "IX_WaitlistEntries_UserId" ON "WaitlistEntries" ("UserId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Tags"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Tags") + 1,
        nextval(pg_get_serial_sequence('"Tags"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310233948_InitialCreate', '9.0.3');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260311004513_InitialCreate2', '9.0.3');

COMMIT;

